### ISSUE TITLE
Asking for help in not getting data from market data

### ISSUE THREAD

**Issue by magiclevinho** [rozzac90/pinnacle#13]
Dear rozzac90,

Could you help me why am I not getting data for the following:
api.market_data.get_line(sport_id=29, league_id=163787, event_id=854626664, period_number=0,
                         bet_type='MONEYLINE', team='DRAW', side=None, handicap=None, odds_format='DECIMAL')

**Comment by magiclevinho** [comment]
Also I can t get the odds!

**Comment by magiclevinho** [comment]
Is this wrapper still working?

**Comment by rozzac90** [comment]
I have account issues at the moment so can't check whether it's working. I dont see much having changed in the api though. Do you have any errors/output returned?

**Comment by magiclevinho** [comment]
Only getting status "NOT EXIST", and zero values. For the odds, I  get JSON error.

**Comment by magiclevinho** [comment]
Good news!
Now some days later, it is working! I don't know what was the error?!

**Comment by rozzac90** [comment]
could it be that the event had finished or the line was no longer available?

**Comment by magiclevinho** [comment]
No, I double checked the 3 arbitrary chosen matches. They were before kickoff, and available on the pinnacle website. I didn't verify more matches then.

**Comment by rozzac90** [comment]
That's quite strange I know they do change the event ids so if there was along period between the query to get the matches and the failing query it may have been relisted under a new I'd. I will close this issue for now as it seems to be fixed
