### ISSUE TITLE
Error while installing pinnacle wrapper

### ISSUE THREAD

**Issue by magiclevinho** [rozzac90/pinnacle#2]
I m using win10, python 2.7.
When I try to install the wrapper i get the following error:
> Collecting pinnacle
>   Downloading pinnacle-0.0.4.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "c:\users\john\appdata\local\temp\pip-build-db6bbp\pinnacle\setup.py", line 3, in <module>
>         from pinnacle import __version__
>       File "pinnacle\__init__.py", line 1, in <module>
>         from pinnacle.apiclient import APIClient
>       File "pinnacle\apiclient.py", line 2, in <module>
>         from pinnacle import endpoints
>       File "pinnacle\endpoints\__init__.py", line 3, in <module>
>         from pinnacle.endpoints.betting import Betting
>       File "pinnacle\endpoints\betting.py", line 46
>     SyntaxError: Non-ASCII character '\xe2' in file pinnacle\endpoints\betting.py on line 47, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in c:\users\john\appdata\local\temp\pip-build-db6bbp\pinnacle\
> 

Any help would be appreciated!

**Comment by rozzac90** [comment]
Hey mate,

Apologies for the delay in getting back to you I haven't had a chance to check this out yet. I have been running all of my testing etc. on python 3.6 which is where the problem with import on 2.7 is arising. I will add encoding, test and push an update to pypi in the coming days.

Thanks for spotting this and raising the issue.

**Comment by magiclevinho** [comment]
Thank You for Your work!

**Comment by ldrapeau** [comment]
Same here, ubuntu server 16.04 with Python 2.7.12 (default, Nov 19 2016, 06:48:10)

**Comment by ldrapeau** [comment]
Hello,  

I seem to have the same issue,  All my other programs are python 2.  Many thanks for your work, look forward to having automated access to line moves and betting.  Here is my output:

cildadmin@sue:~$ pip install pinnacle
Collecting pinnacle
  Using cached pinnacle-0.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-b3EeJY/pinnacle/setup.py", line 3, in <module>
        from pinnacle import __version__
      File "/tmp/pip-build-b3EeJY/pinnacle/pinnacle/__init__.py", line 1, in <module>
        from pinnacle.apiclient import APIClient
      File "/tmp/pip-build-b3EeJY/pinnacle/pinnacle/apiclient.py", line 2, in <module>
        from pinnacle import endpoints
      File "/tmp/pip-build-b3EeJY/pinnacle/pinnacle/endpoints/__init__.py", line 3, in <module>
        from pinnacle.endpoints.betting import Betting
      File "/tmp/pip-build-b3EeJY/pinnacle/pinnacle/endpoints/betting.py", line 46
    SyntaxError: Non-ASCII character '\xe2' in file /tmp/pip-build-b3EeJY/pinnacle/pinnacle/endpoints/betting.py on line 47, but no enc
oding declared; see http://python.org/dev/peps/pep-0263/ for details

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-b3EeJY/pinnacle/
cildadmin@sue:~$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by rozzac90** [comment]
I think this should be fixed now, version 0.0.5 uploaded to pypi.

**Comment by ldrapeau** [comment]
Super!  Worked fine for me, many thanks for the great wrapper.  Louis

**Comment by rozzac90** [comment]
Going to close this off then, please raise any further issues I don't have access to a Pinnacle account at the moment to run testing so no doubt there are more bugs floating around.
