### ISSUE TITLE
get fixture issue using since parameter when sport_id=34 (volleyball)

### ISSUE THREAD

**Issue by rkamika** [rozzac90/pinnacle#20]
Hello @rozzac90 ,
I'm trying to retrieve fixtures using since parameter, but I'm getting some error. Note, that this only happened when I used sport_id=34 (volleyball).
I tested using sport_id=33 (tennis) and it worked perfectly.

Do you have any idea what it can be?

![image](https://user-images.githubusercontent.com/45544468/49345793-fa3ef480-f670-11e8-98b2-de72cf097d96.png)

![image](https://user-images.githubusercontent.com/45544468/49345789-f0b58c80-f670-11e8-8cae-df028ce83b6b.png)

Thank you very much,
Rodrigo

**Comment by rozzac90** [comment]
Looks like the API call returns no data so you get this error trying to retrieve json from the request.

**Comment by rkamika** [comment]
Got it. I'm going to handle that.
Thank you very much
